// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pkcs11 "github.com/miekg/pkcs11"
	mock "github.com/stretchr/testify/mock"
)

// MockCryptoki is an autogenerated mock type for the Cryptoki type
type MockCryptoki struct {
	mock.Mock
}

type MockCryptoki_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptoki) EXPECT() *MockCryptoki_Expecter {
	return &MockCryptoki_Expecter{mock: &_m.Mock}
}

// CloseSession provides a mock function with given fields: sh
func (_m *MockCryptoki) CloseSession(sh pkcs11.SessionHandle) error {
	ret := _m.Called(sh)

	if len(ret) == 0 {
		panic("no return value specified for CloseSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle) error); ok {
		r0 = rf(sh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_CloseSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSession'
type MockCryptoki_CloseSession_Call struct {
	*mock.Call
}

// CloseSession is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
func (_e *MockCryptoki_Expecter) CloseSession(sh interface{}) *MockCryptoki_CloseSession_Call {
	return &MockCryptoki_CloseSession_Call{Call: _e.mock.On("CloseSession", sh)}
}

func (_c *MockCryptoki_CloseSession_Call) Run(run func(sh pkcs11.SessionHandle)) *MockCryptoki_CloseSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle))
	})
	return _c
}

func (_c *MockCryptoki_CloseSession_Call) Return(_a0 error) *MockCryptoki_CloseSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_CloseSession_Call) RunAndReturn(run func(pkcs11.SessionHandle) error) *MockCryptoki_CloseSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateObject provides a mock function with given fields: sh, temp
func (_m *MockCryptoki) CreateObject(sh pkcs11.SessionHandle, temp []*pkcs11.Attribute) (pkcs11.ObjectHandle, error) {
	ret := _m.Called(sh, temp)

	if len(ret) == 0 {
		panic("no return value specified for CreateObject")
	}

	var r0 pkcs11.ObjectHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)); ok {
		return rf(sh, temp)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Attribute) pkcs11.ObjectHandle); ok {
		r0 = rf(sh, temp)
	} else {
		r0 = ret.Get(0).(pkcs11.ObjectHandle)
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []*pkcs11.Attribute) error); ok {
		r1 = rf(sh, temp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_CreateObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateObject'
type MockCryptoki_CreateObject_Call struct {
	*mock.Call
}

// CreateObject is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - temp []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) CreateObject(sh interface{}, temp interface{}) *MockCryptoki_CreateObject_Call {
	return &MockCryptoki_CreateObject_Call{Call: _e.mock.On("CreateObject", sh, temp)}
}

func (_c *MockCryptoki_CreateObject_Call) Run(run func(sh pkcs11.SessionHandle, temp []*pkcs11.Attribute)) *MockCryptoki_CreateObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_CreateObject_Call) Return(_a0 pkcs11.ObjectHandle, _a1 error) *MockCryptoki_CreateObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_CreateObject_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)) *MockCryptoki_CreateObject_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with no fields
func (_m *MockCryptoki) Destroy() {
	_m.Called()
}

// MockCryptoki_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockCryptoki_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockCryptoki_Expecter) Destroy() *MockCryptoki_Destroy_Call {
	return &MockCryptoki_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockCryptoki_Destroy_Call) Run(run func()) *MockCryptoki_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCryptoki_Destroy_Call) Return() *MockCryptoki_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCryptoki_Destroy_Call) RunAndReturn(run func()) *MockCryptoki_Destroy_Call {
	_c.Run(run)
	return _c
}

// DestroyObject provides a mock function with given fields: sh, oh
func (_m *MockCryptoki) DestroyObject(sh pkcs11.SessionHandle, oh pkcs11.ObjectHandle) error {
	ret := _m.Called(sh, oh)

	if len(ret) == 0 {
		panic("no return value specified for DestroyObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, pkcs11.ObjectHandle) error); ok {
		r0 = rf(sh, oh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_DestroyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyObject'
type MockCryptoki_DestroyObject_Call struct {
	*mock.Call
}

// DestroyObject is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - oh pkcs11.ObjectHandle
func (_e *MockCryptoki_Expecter) DestroyObject(sh interface{}, oh interface{}) *MockCryptoki_DestroyObject_Call {
	return &MockCryptoki_DestroyObject_Call{Call: _e.mock.On("DestroyObject", sh, oh)}
}

func (_c *MockCryptoki_DestroyObject_Call) Run(run func(sh pkcs11.SessionHandle, oh pkcs11.ObjectHandle)) *MockCryptoki_DestroyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].(pkcs11.ObjectHandle))
	})
	return _c
}

func (_c *MockCryptoki_DestroyObject_Call) Return(_a0 error) *MockCryptoki_DestroyObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_DestroyObject_Call) RunAndReturn(run func(pkcs11.SessionHandle, pkcs11.ObjectHandle) error) *MockCryptoki_DestroyObject_Call {
	_c.Call.Return(run)
	return _c
}

// Finalize provides a mock function with no fields
func (_m *MockCryptoki) Finalize() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finalize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_Finalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finalize'
type MockCryptoki_Finalize_Call struct {
	*mock.Call
}

// Finalize is a helper method to define mock.On call
func (_e *MockCryptoki_Expecter) Finalize() *MockCryptoki_Finalize_Call {
	return &MockCryptoki_Finalize_Call{Call: _e.mock.On("Finalize")}
}

func (_c *MockCryptoki_Finalize_Call) Run(run func()) *MockCryptoki_Finalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCryptoki_Finalize_Call) Return(_a0 error) *MockCryptoki_Finalize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_Finalize_Call) RunAndReturn(run func() error) *MockCryptoki_Finalize_Call {
	_c.Call.Return(run)
	return _c
}

// FindObjects provides a mock function with given fields: sh, max
func (_m *MockCryptoki) FindObjects(sh pkcs11.SessionHandle, max int) ([]pkcs11.ObjectHandle, bool, error) {
	ret := _m.Called(sh, max)

	if len(ret) == 0 {
		panic("no return value specified for FindObjects")
	}

	var r0 []pkcs11.ObjectHandle
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, int) ([]pkcs11.ObjectHandle, bool, error)); ok {
		return rf(sh, max)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, int) []pkcs11.ObjectHandle); ok {
		r0 = rf(sh, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkcs11.ObjectHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, int) bool); ok {
		r1 = rf(sh, max)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(pkcs11.SessionHandle, int) error); ok {
		r2 = rf(sh, max)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCryptoki_FindObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindObjects'
type MockCryptoki_FindObjects_Call struct {
	*mock.Call
}

// FindObjects is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - max int
func (_e *MockCryptoki_Expecter) FindObjects(sh interface{}, max interface{}) *MockCryptoki_FindObjects_Call {
	return &MockCryptoki_FindObjects_Call{Call: _e.mock.On("FindObjects", sh, max)}
}

func (_c *MockCryptoki_FindObjects_Call) Run(run func(sh pkcs11.SessionHandle, max int)) *MockCryptoki_FindObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].(int))
	})
	return _c
}

func (_c *MockCryptoki_FindObjects_Call) Return(_a0 []pkcs11.ObjectHandle, _a1 bool, _a2 error) *MockCryptoki_FindObjects_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCryptoki_FindObjects_Call) RunAndReturn(run func(pkcs11.SessionHandle, int) ([]pkcs11.ObjectHandle, bool, error)) *MockCryptoki_FindObjects_Call {
	_c.Call.Return(run)
	return _c
}

// FindObjectsFinal provides a mock function with given fields: sh
func (_m *MockCryptoki) FindObjectsFinal(sh pkcs11.SessionHandle) error {
	ret := _m.Called(sh)

	if len(ret) == 0 {
		panic("no return value specified for FindObjectsFinal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle) error); ok {
		r0 = rf(sh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_FindObjectsFinal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindObjectsFinal'
type MockCryptoki_FindObjectsFinal_Call struct {
	*mock.Call
}

// FindObjectsFinal is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
func (_e *MockCryptoki_Expecter) FindObjectsFinal(sh interface{}) *MockCryptoki_FindObjectsFinal_Call {
	return &MockCryptoki_FindObjectsFinal_Call{Call: _e.mock.On("FindObjectsFinal", sh)}
}

func (_c *MockCryptoki_FindObjectsFinal_Call) Run(run func(sh pkcs11.SessionHandle)) *MockCryptoki_FindObjectsFinal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle))
	})
	return _c
}

func (_c *MockCryptoki_FindObjectsFinal_Call) Return(_a0 error) *MockCryptoki_FindObjectsFinal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_FindObjectsFinal_Call) RunAndReturn(run func(pkcs11.SessionHandle) error) *MockCryptoki_FindObjectsFinal_Call {
	_c.Call.Return(run)
	return _c
}

// FindObjectsInit provides a mock function with given fields: sh, temp
func (_m *MockCryptoki) FindObjectsInit(sh pkcs11.SessionHandle, temp []*pkcs11.Attribute) error {
	ret := _m.Called(sh, temp)

	if len(ret) == 0 {
		panic("no return value specified for FindObjectsInit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Attribute) error); ok {
		r0 = rf(sh, temp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_FindObjectsInit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindObjectsInit'
type MockCryptoki_FindObjectsInit_Call struct {
	*mock.Call
}

// FindObjectsInit is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - temp []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) FindObjectsInit(sh interface{}, temp interface{}) *MockCryptoki_FindObjectsInit_Call {
	return &MockCryptoki_FindObjectsInit_Call{Call: _e.mock.On("FindObjectsInit", sh, temp)}
}

func (_c *MockCryptoki_FindObjectsInit_Call) Run(run func(sh pkcs11.SessionHandle, temp []*pkcs11.Attribute)) *MockCryptoki_FindObjectsInit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_FindObjectsInit_Call) Return(_a0 error) *MockCryptoki_FindObjectsInit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_FindObjectsInit_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Attribute) error) *MockCryptoki_FindObjectsInit_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateKey provides a mock function with given fields: sh, m, temp
func (_m *MockCryptoki) GenerateKey(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, temp []*pkcs11.Attribute) (pkcs11.ObjectHandle, error) {
	ret := _m.Called(sh, m, temp)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 pkcs11.ObjectHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)); ok {
		return rf(sh, m, temp)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute) pkcs11.ObjectHandle); ok {
		r0 = rf(sh, m, temp)
	} else {
		r0 = ret.Get(0).(pkcs11.ObjectHandle)
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute) error); ok {
		r1 = rf(sh, m, temp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockCryptoki_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - m []*pkcs11.Mechanism
//   - temp []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) GenerateKey(sh interface{}, m interface{}, temp interface{}) *MockCryptoki_GenerateKey_Call {
	return &MockCryptoki_GenerateKey_Call{Call: _e.mock.On("GenerateKey", sh, m, temp)}
}

func (_c *MockCryptoki_GenerateKey_Call) Run(run func(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, temp []*pkcs11.Attribute)) *MockCryptoki_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Mechanism), args[2].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_GenerateKey_Call) Return(_a0 pkcs11.ObjectHandle, _a1 error) *MockCryptoki_GenerateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GenerateKey_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)) *MockCryptoki_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateKeyPair provides a mock function with given fields: sh, m, public, private
func (_m *MockCryptoki) GenerateKeyPair(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, public []*pkcs11.Attribute, private []*pkcs11.Attribute) (pkcs11.ObjectHandle, pkcs11.ObjectHandle, error) {
	ret := _m.Called(sh, m, public, private)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKeyPair")
	}

	var r0 pkcs11.ObjectHandle
	var r1 pkcs11.ObjectHandle
	var r2 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute, []*pkcs11.Attribute) (pkcs11.ObjectHandle, pkcs11.ObjectHandle, error)); ok {
		return rf(sh, m, public, private)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute, []*pkcs11.Attribute) pkcs11.ObjectHandle); ok {
		r0 = rf(sh, m, public, private)
	} else {
		r0 = ret.Get(0).(pkcs11.ObjectHandle)
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute, []*pkcs11.Attribute) pkcs11.ObjectHandle); ok {
		r1 = rf(sh, m, public, private)
	} else {
		r1 = ret.Get(1).(pkcs11.ObjectHandle)
	}

	if rf, ok := ret.Get(2).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute, []*pkcs11.Attribute) error); ok {
		r2 = rf(sh, m, public, private)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCryptoki_GenerateKeyPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKeyPair'
type MockCryptoki_GenerateKeyPair_Call struct {
	*mock.Call
}

// GenerateKeyPair is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - m []*pkcs11.Mechanism
//   - public []*pkcs11.Attribute
//   - private []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) GenerateKeyPair(sh interface{}, m interface{}, public interface{}, private interface{}) *MockCryptoki_GenerateKeyPair_Call {
	return &MockCryptoki_GenerateKeyPair_Call{Call: _e.mock.On("GenerateKeyPair", sh, m, public, private)}
}

func (_c *MockCryptoki_GenerateKeyPair_Call) Run(run func(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, public []*pkcs11.Attribute, private []*pkcs11.Attribute)) *MockCryptoki_GenerateKeyPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Mechanism), args[2].([]*pkcs11.Attribute), args[3].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_GenerateKeyPair_Call) Return(_a0 pkcs11.ObjectHandle, _a1 pkcs11.ObjectHandle, _a2 error) *MockCryptoki_GenerateKeyPair_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCryptoki_GenerateKeyPair_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Mechanism, []*pkcs11.Attribute, []*pkcs11.Attribute) (pkcs11.ObjectHandle, pkcs11.ObjectHandle, error)) *MockCryptoki_GenerateKeyPair_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributeValue provides a mock function with given fields: sh, o, a
func (_m *MockCryptoki) GetAttributeValue(sh pkcs11.SessionHandle, o pkcs11.ObjectHandle, a []*pkcs11.Attribute) ([]*pkcs11.Attribute, error) {
	ret := _m.Called(sh, o, a)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributeValue")
	}

	var r0 []*pkcs11.Attribute
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, pkcs11.ObjectHandle, []*pkcs11.Attribute) ([]*pkcs11.Attribute, error)); ok {
		return rf(sh, o, a)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, pkcs11.ObjectHandle, []*pkcs11.Attribute) []*pkcs11.Attribute); ok {
		r0 = rf(sh, o, a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkcs11.Attribute)
		}
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, pkcs11.ObjectHandle, []*pkcs11.Attribute) error); ok {
		r1 = rf(sh, o, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetAttributeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributeValue'
type MockCryptoki_GetAttributeValue_Call struct {
	*mock.Call
}

// GetAttributeValue is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - o pkcs11.ObjectHandle
//   - a []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) GetAttributeValue(sh interface{}, o interface{}, a interface{}) *MockCryptoki_GetAttributeValue_Call {
	return &MockCryptoki_GetAttributeValue_Call{Call: _e.mock.On("GetAttributeValue", sh, o, a)}
}

func (_c *MockCryptoki_GetAttributeValue_Call) Run(run func(sh pkcs11.SessionHandle, o pkcs11.ObjectHandle, a []*pkcs11.Attribute)) *MockCryptoki_GetAttributeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].(pkcs11.ObjectHandle), args[2].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_GetAttributeValue_Call) Return(_a0 []*pkcs11.Attribute, _a1 error) *MockCryptoki_GetAttributeValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetAttributeValue_Call) RunAndReturn(run func(pkcs11.SessionHandle, pkcs11.ObjectHandle, []*pkcs11.Attribute) ([]*pkcs11.Attribute, error)) *MockCryptoki_GetAttributeValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function with no fields
func (_m *MockCryptoki) GetInfo() (pkcs11.Info, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 pkcs11.Info
	var r1 error
	if rf, ok := ret.Get(0).(func() (pkcs11.Info, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() pkcs11.Info); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pkcs11.Info)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockCryptoki_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
func (_e *MockCryptoki_Expecter) GetInfo() *MockCryptoki_GetInfo_Call {
	return &MockCryptoki_GetInfo_Call{Call: _e.mock.On("GetInfo")}
}

func (_c *MockCryptoki_GetInfo_Call) Run(run func()) *MockCryptoki_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCryptoki_GetInfo_Call) Return(_a0 pkcs11.Info, _a1 error) *MockCryptoki_GetInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetInfo_Call) RunAndReturn(run func() (pkcs11.Info, error)) *MockCryptoki_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMechanismInfo provides a mock function with given fields: slotID, m
func (_m *MockCryptoki) GetMechanismInfo(slotID uint, m []*pkcs11.Mechanism) (pkcs11.MechanismInfo, error) {
	ret := _m.Called(slotID, m)

	if len(ret) == 0 {
		panic("no return value specified for GetMechanismInfo")
	}

	var r0 pkcs11.MechanismInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, []*pkcs11.Mechanism) (pkcs11.MechanismInfo, error)); ok {
		return rf(slotID, m)
	}
	if rf, ok := ret.Get(0).(func(uint, []*pkcs11.Mechanism) pkcs11.MechanismInfo); ok {
		r0 = rf(slotID, m)
	} else {
		r0 = ret.Get(0).(pkcs11.MechanismInfo)
	}

	if rf, ok := ret.Get(1).(func(uint, []*pkcs11.Mechanism) error); ok {
		r1 = rf(slotID, m)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetMechanismInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMechanismInfo'
type MockCryptoki_GetMechanismInfo_Call struct {
	*mock.Call
}

// GetMechanismInfo is a helper method to define mock.On call
//   - slotID uint
//   - m []*pkcs11.Mechanism
func (_e *MockCryptoki_Expecter) GetMechanismInfo(slotID interface{}, m interface{}) *MockCryptoki_GetMechanismInfo_Call {
	return &MockCryptoki_GetMechanismInfo_Call{Call: _e.mock.On("GetMechanismInfo", slotID, m)}
}

func (_c *MockCryptoki_GetMechanismInfo_Call) Run(run func(slotID uint, m []*pkcs11.Mechanism)) *MockCryptoki_GetMechanismInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].([]*pkcs11.Mechanism))
	})
	return _c
}

func (_c *MockCryptoki_GetMechanismInfo_Call) Return(_a0 pkcs11.MechanismInfo, _a1 error) *MockCryptoki_GetMechanismInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetMechanismInfo_Call) RunAndReturn(run func(uint, []*pkcs11.Mechanism) (pkcs11.MechanismInfo, error)) *MockCryptoki_GetMechanismInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMechanismList provides a mock function with given fields: slotID
func (_m *MockCryptoki) GetMechanismList(slotID uint) ([]*pkcs11.Mechanism, error) {
	ret := _m.Called(slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetMechanismList")
	}

	var r0 []*pkcs11.Mechanism
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]*pkcs11.Mechanism, error)); ok {
		return rf(slotID)
	}
	if rf, ok := ret.Get(0).(func(uint) []*pkcs11.Mechanism); ok {
		r0 = rf(slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkcs11.Mechanism)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetMechanismList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMechanismList'
type MockCryptoki_GetMechanismList_Call struct {
	*mock.Call
}

// GetMechanismList is a helper method to define mock.On call
//   - slotID uint
func (_e *MockCryptoki_Expecter) GetMechanismList(slotID interface{}) *MockCryptoki_GetMechanismList_Call {
	return &MockCryptoki_GetMechanismList_Call{Call: _e.mock.On("GetMechanismList", slotID)}
}

func (_c *MockCryptoki_GetMechanismList_Call) Run(run func(slotID uint)) *MockCryptoki_GetMechanismList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCryptoki_GetMechanismList_Call) Return(_a0 []*pkcs11.Mechanism, _a1 error) *MockCryptoki_GetMechanismList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetMechanismList_Call) RunAndReturn(run func(uint) ([]*pkcs11.Mechanism, error)) *MockCryptoki_GetMechanismList_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotInfo provides a mock function with given fields: slotID
func (_m *MockCryptoki) GetSlotInfo(slotID uint) (pkcs11.SlotInfo, error) {
	ret := _m.Called(slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotInfo")
	}

	var r0 pkcs11.SlotInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (pkcs11.SlotInfo, error)); ok {
		return rf(slotID)
	}
	if rf, ok := ret.Get(0).(func(uint) pkcs11.SlotInfo); ok {
		r0 = rf(slotID)
	} else {
		r0 = ret.Get(0).(pkcs11.SlotInfo)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetSlotInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotInfo'
type MockCryptoki_GetSlotInfo_Call struct {
	*mock.Call
}

// GetSlotInfo is a helper method to define mock.On call
//   - slotID uint
func (_e *MockCryptoki_Expecter) GetSlotInfo(slotID interface{}) *MockCryptoki_GetSlotInfo_Call {
	return &MockCryptoki_GetSlotInfo_Call{Call: _e.mock.On("GetSlotInfo", slotID)}
}

func (_c *MockCryptoki_GetSlotInfo_Call) Run(run func(slotID uint)) *MockCryptoki_GetSlotInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCryptoki_GetSlotInfo_Call) Return(_a0 pkcs11.SlotInfo, _a1 error) *MockCryptoki_GetSlotInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetSlotInfo_Call) RunAndReturn(run func(uint) (pkcs11.SlotInfo, error)) *MockCryptoki_GetSlotInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetSlotList provides a mock function with given fields: tokenPresent
func (_m *MockCryptoki) GetSlotList(tokenPresent bool) ([]uint, error) {
	ret := _m.Called(tokenPresent)

	if len(ret) == 0 {
		panic("no return value specified for GetSlotList")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(bool) ([]uint, error)); ok {
		return rf(tokenPresent)
	}
	if rf, ok := ret.Get(0).(func(bool) []uint); ok {
		r0 = rf(tokenPresent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(tokenPresent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetSlotList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlotList'
type MockCryptoki_GetSlotList_Call struct {
	*mock.Call
}

// GetSlotList is a helper method to define mock.On call
//   - tokenPresent bool
func (_e *MockCryptoki_Expecter) GetSlotList(tokenPresent interface{}) *MockCryptoki_GetSlotList_Call {
	return &MockCryptoki_GetSlotList_Call{Call: _e.mock.On("GetSlotList", tokenPresent)}
}

func (_c *MockCryptoki_GetSlotList_Call) Run(run func(tokenPresent bool)) *MockCryptoki_GetSlotList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockCryptoki_GetSlotList_Call) Return(_a0 []uint, _a1 error) *MockCryptoki_GetSlotList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetSlotList_Call) RunAndReturn(run func(bool) ([]uint, error)) *MockCryptoki_GetSlotList_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenInfo provides a mock function with given fields: slotID
func (_m *MockCryptoki) GetTokenInfo(slotID uint) (pkcs11.TokenInfo, error) {
	ret := _m.Called(slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 pkcs11.TokenInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (pkcs11.TokenInfo, error)); ok {
		return rf(slotID)
	}
	if rf, ok := ret.Get(0).(func(uint) pkcs11.TokenInfo); ok {
		r0 = rf(slotID)
	} else {
		r0 = ret.Get(0).(pkcs11.TokenInfo)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_GetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenInfo'
type MockCryptoki_GetTokenInfo_Call struct {
	*mock.Call
}

// GetTokenInfo is a helper method to define mock.On call
//   - slotID uint
func (_e *MockCryptoki_Expecter) GetTokenInfo(slotID interface{}) *MockCryptoki_GetTokenInfo_Call {
	return &MockCryptoki_GetTokenInfo_Call{Call: _e.mock.On("GetTokenInfo", slotID)}
}

func (_c *MockCryptoki_GetTokenInfo_Call) Run(run func(slotID uint)) *MockCryptoki_GetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCryptoki_GetTokenInfo_Call) Return(_a0 pkcs11.TokenInfo, _a1 error) *MockCryptoki_GetTokenInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_GetTokenInfo_Call) RunAndReturn(run func(uint) (pkcs11.TokenInfo, error)) *MockCryptoki_GetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function with given fields: opts
func (_m *MockCryptoki) Initialize(opts ...pkcs11.InitializeOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...pkcs11.InitializeOption) error); ok {
		r0 = rf(opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockCryptoki_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - opts ...pkcs11.InitializeOption
func (_e *MockCryptoki_Expecter) Initialize(opts ...interface{}) *MockCryptoki_Initialize_Call {
	return &MockCryptoki_Initialize_Call{Call: _e.mock.On("Initialize",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockCryptoki_Initialize_Call) Run(run func(opts ...pkcs11.InitializeOption)) *MockCryptoki_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]pkcs11.InitializeOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(pkcs11.InitializeOption)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockCryptoki_Initialize_Call) Return(_a0 error) *MockCryptoki_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_Initialize_Call) RunAndReturn(run func(...pkcs11.InitializeOption) error) *MockCryptoki_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: sh, userType, pin
func (_m *MockCryptoki) Login(sh pkcs11.SessionHandle, userType uint, pin string) error {
	ret := _m.Called(sh, userType, pin)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, uint, string) error); ok {
		r0 = rf(sh, userType, pin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockCryptoki_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - userType uint
//   - pin string
func (_e *MockCryptoki_Expecter) Login(sh interface{}, userType interface{}, pin interface{}) *MockCryptoki_Login_Call {
	return &MockCryptoki_Login_Call{Call: _e.mock.On("Login", sh, userType, pin)}
}

func (_c *MockCryptoki_Login_Call) Run(run func(sh pkcs11.SessionHandle, userType uint, pin string)) *MockCryptoki_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockCryptoki_Login_Call) Return(_a0 error) *MockCryptoki_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_Login_Call) RunAndReturn(run func(pkcs11.SessionHandle, uint, string) error) *MockCryptoki_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: sh
func (_m *MockCryptoki) Logout(sh pkcs11.SessionHandle) error {
	ret := _m.Called(sh)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle) error); ok {
		r0 = rf(sh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockCryptoki_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
func (_e *MockCryptoki_Expecter) Logout(sh interface{}) *MockCryptoki_Logout_Call {
	return &MockCryptoki_Logout_Call{Call: _e.mock.On("Logout", sh)}
}

func (_c *MockCryptoki_Logout_Call) Run(run func(sh pkcs11.SessionHandle)) *MockCryptoki_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle))
	})
	return _c
}

func (_c *MockCryptoki_Logout_Call) Return(_a0 error) *MockCryptoki_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_Logout_Call) RunAndReturn(run func(pkcs11.SessionHandle) error) *MockCryptoki_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// OpenSession provides a mock function with given fields: slotID, flags
func (_m *MockCryptoki) OpenSession(slotID uint, flags uint) (pkcs11.SessionHandle, error) {
	ret := _m.Called(slotID, flags)

	if len(ret) == 0 {
		panic("no return value specified for OpenSession")
	}

	var r0 pkcs11.SessionHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (pkcs11.SessionHandle, error)); ok {
		return rf(slotID, flags)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) pkcs11.SessionHandle); ok {
		r0 = rf(slotID, flags)
	} else {
		r0 = ret.Get(0).(pkcs11.SessionHandle)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(slotID, flags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_OpenSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenSession'
type MockCryptoki_OpenSession_Call struct {
	*mock.Call
}

// OpenSession is a helper method to define mock.On call
//   - slotID uint
//   - flags uint
func (_e *MockCryptoki_Expecter) OpenSession(slotID interface{}, flags interface{}) *MockCryptoki_OpenSession_Call {
	return &MockCryptoki_OpenSession_Call{Call: _e.mock.On("OpenSession", slotID, flags)}
}

func (_c *MockCryptoki_OpenSession_Call) Run(run func(slotID uint, flags uint)) *MockCryptoki_OpenSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(uint))
	})
	return _c
}

func (_c *MockCryptoki_OpenSession_Call) Return(_a0 pkcs11.SessionHandle, _a1 error) *MockCryptoki_OpenSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_OpenSession_Call) RunAndReturn(run func(uint, uint) (pkcs11.SessionHandle, error)) *MockCryptoki_OpenSession_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function with given fields: sh, message
func (_m *MockCryptoki) Sign(sh pkcs11.SessionHandle, message []byte) ([]byte, error) {
	ret := _m.Called(sh, message)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []byte) ([]byte, error)); ok {
		return rf(sh, message)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []byte) []byte); ok {
		r0 = rf(sh, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []byte) error); ok {
		r1 = rf(sh, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockCryptoki_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - message []byte
func (_e *MockCryptoki_Expecter) Sign(sh interface{}, message interface{}) *MockCryptoki_Sign_Call {
	return &MockCryptoki_Sign_Call{Call: _e.mock.On("Sign", sh, message)}
}

func (_c *MockCryptoki_Sign_Call) Run(run func(sh pkcs11.SessionHandle, message []byte)) *MockCryptoki_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]byte))
	})
	return _c
}

func (_c *MockCryptoki_Sign_Call) Return(_a0 []byte, _a1 error) *MockCryptoki_Sign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_Sign_Call) RunAndReturn(run func(pkcs11.SessionHandle, []byte) ([]byte, error)) *MockCryptoki_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignInit provides a mock function with given fields: sh, m, o
func (_m *MockCryptoki) SignInit(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, o pkcs11.ObjectHandle) error {
	ret := _m.Called(sh, m, o)

	if len(ret) == 0 {
		panic("no return value specified for SignInit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle) error); ok {
		r0 = rf(sh, m, o)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCryptoki_SignInit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInit'
type MockCryptoki_SignInit_Call struct {
	*mock.Call
}

// SignInit is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - m []*pkcs11.Mechanism
//   - o pkcs11.ObjectHandle
func (_e *MockCryptoki_Expecter) SignInit(sh interface{}, m interface{}, o interface{}) *MockCryptoki_SignInit_Call {
	return &MockCryptoki_SignInit_Call{Call: _e.mock.On("SignInit", sh, m, o)}
}

func (_c *MockCryptoki_SignInit_Call) Run(run func(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, o pkcs11.ObjectHandle)) *MockCryptoki_SignInit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Mechanism), args[2].(pkcs11.ObjectHandle))
	})
	return _c
}

func (_c *MockCryptoki_SignInit_Call) Return(_a0 error) *MockCryptoki_SignInit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptoki_SignInit_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle) error) *MockCryptoki_SignInit_Call {
	_c.Call.Return(run)
	return _c
}

// UnwrapKey provides a mock function with given fields: sh, m, unwrappingkey, wrappedkey, a
func (_m *MockCryptoki) UnwrapKey(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, unwrappingkey pkcs11.ObjectHandle, wrappedkey []byte, a []*pkcs11.Attribute) (pkcs11.ObjectHandle, error) {
	ret := _m.Called(sh, m, unwrappingkey, wrappedkey, a)

	if len(ret) == 0 {
		panic("no return value specified for UnwrapKey")
	}

	var r0 pkcs11.ObjectHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, []byte, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)); ok {
		return rf(sh, m, unwrappingkey, wrappedkey, a)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, []byte, []*pkcs11.Attribute) pkcs11.ObjectHandle); ok {
		r0 = rf(sh, m, unwrappingkey, wrappedkey, a)
	} else {
		r0 = ret.Get(0).(pkcs11.ObjectHandle)
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, []byte, []*pkcs11.Attribute) error); ok {
		r1 = rf(sh, m, unwrappingkey, wrappedkey, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_UnwrapKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnwrapKey'
type MockCryptoki_UnwrapKey_Call struct {
	*mock.Call
}

// UnwrapKey is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - m []*pkcs11.Mechanism
//   - unwrappingkey pkcs11.ObjectHandle
//   - wrappedkey []byte
//   - a []*pkcs11.Attribute
func (_e *MockCryptoki_Expecter) UnwrapKey(sh interface{}, m interface{}, unwrappingkey interface{}, wrappedkey interface{}, a interface{}) *MockCryptoki_UnwrapKey_Call {
	return &MockCryptoki_UnwrapKey_Call{Call: _e.mock.On("UnwrapKey", sh, m, unwrappingkey, wrappedkey, a)}
}

func (_c *MockCryptoki_UnwrapKey_Call) Run(run func(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, unwrappingkey pkcs11.ObjectHandle, wrappedkey []byte, a []*pkcs11.Attribute)) *MockCryptoki_UnwrapKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Mechanism), args[2].(pkcs11.ObjectHandle), args[3].([]byte), args[4].([]*pkcs11.Attribute))
	})
	return _c
}

func (_c *MockCryptoki_UnwrapKey_Call) Return(_a0 pkcs11.ObjectHandle, _a1 error) *MockCryptoki_UnwrapKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_UnwrapKey_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, []byte, []*pkcs11.Attribute) (pkcs11.ObjectHandle, error)) *MockCryptoki_UnwrapKey_Call {
	_c.Call.Return(run)
	return _c
}

// WrapKey provides a mock function with given fields: sh, m, wrappingkey, key
func (_m *MockCryptoki) WrapKey(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, wrappingkey pkcs11.ObjectHandle, key pkcs11.ObjectHandle) ([]byte, error) {
	ret := _m.Called(sh, m, wrappingkey, key)

	if len(ret) == 0 {
		panic("no return value specified for WrapKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, pkcs11.ObjectHandle) ([]byte, error)); ok {
		return rf(sh, m, wrappingkey, key)
	}
	if rf, ok := ret.Get(0).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, pkcs11.ObjectHandle) []byte); ok {
		r0 = rf(sh, m, wrappingkey, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, pkcs11.ObjectHandle) error); ok {
		r1 = rf(sh, m, wrappingkey, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptoki_WrapKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapKey'
type MockCryptoki_WrapKey_Call struct {
	*mock.Call
}

// WrapKey is a helper method to define mock.On call
//   - sh pkcs11.SessionHandle
//   - m []*pkcs11.Mechanism
//   - wrappingkey pkcs11.ObjectHandle
//   - key pkcs11.ObjectHandle
func (_e *MockCryptoki_Expecter) WrapKey(sh interface{}, m interface{}, wrappingkey interface{}, key interface{}) *MockCryptoki_WrapKey_Call {
	return &MockCryptoki_WrapKey_Call{Call: _e.mock.On("WrapKey", sh, m, wrappingkey, key)}
}

func (_c *MockCryptoki_WrapKey_Call) Run(run func(sh pkcs11.SessionHandle, m []*pkcs11.Mechanism, wrappingkey pkcs11.ObjectHandle, key pkcs11.ObjectHandle)) *MockCryptoki_WrapKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(pkcs11.SessionHandle), args[1].([]*pkcs11.Mechanism), args[2].(pkcs11.ObjectHandle), args[3].(pkcs11.ObjectHandle))
	})
	return _c
}

func (_c *MockCryptoki_WrapKey_Call) Return(_a0 []byte, _a1 error) *MockCryptoki_WrapKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptoki_WrapKey_Call) RunAndReturn(run func(pkcs11.SessionHandle, []*pkcs11.Mechanism, pkcs11.ObjectHandle, pkcs11.ObjectHandle) ([]byte, error)) *MockCryptoki_WrapKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCryptoki creates a new instance of MockCryptoki. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptoki(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptoki {
	mock := &MockCryptoki{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
